export const ADD_RETROSPECTIVE_REQUEST = "ADD_RETROSPECTIVE_REQUEST";
export const ADD_RETROSPECTIVE_SUCCESS = "ADD_RETROSPECTIVE_SUCCESS";
export const ADD_RETROSPECTIVE_FAILURE = "ADD_RETROSPECTIVE_FAILURE";
export const UPDATE_RETROSPECTIVE_REQUEST = "UPDATE_RETROSPECTIVE_REQUEST";
export const UPDATE_RETROSPECTIVE_SUCCESS = "UPDATE_RETROSPECTIVE_SUCCESS";
export const UPDATE_RETROSPECTIVE_FAILURE = "UPDATE_RETROSPECTIVE_FAILURE";
export const DELETE_RETROSPECTIVE_REQUEST = "DELETE_RETROSPECTIVE_REQUEST";
export const DELETE_RETROSPECTIVE_SUCCESS = "DELETE_RETROSPECTIVE_SUCCESS";
export const DELETE_RETROSPECTIVE_FAILURE = "DELETE_RETROSPECTIVE_FAILURE";
export const FETCH_RETROSPECTIVES_REQUEST = "FETCH_RETROSPECTIVES_REQUEST";
export const FETCH_RETROSPECTIVES_SUCCESS = "FETCH_RETROSPECTIVES_SUCCESS";
export const FETCH_RETROSPECTIVES_FAILURE = "FETCH_RETROSPECTIVES_FAILURE";
export const MARK_RETROSPECTIVES_COMPLETE = "MARK_RETROSPECTIVES_COMPLETE";



