export const GET_SELECTED_SPRINT = "get_selected_sprint";
export const SET_SELECTED_SPRINT = "set_selected_sprint";
export const SET_SPRINT_LIST = "SET_SPRINT_LIST";
export const MARK_SPRINT_COMPLETE = "MARK_SPRINT_COMPLETE";
export const START_SPRINT_REQUEST = "START_SPRINT_REQUEST";
export const START_SPRINT_SUCCESS = "START_SPRINT_SUCCESS";
export const START_SPRINT_FAILURE = "START_SPRINT_FAILURE";