export const SET_LOADER_FALSE = "SET_LOADER_FALSE";
export const SET_LOADER_TRUE = "SET_LOADER_TRUE";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";
export const TOGGLE_HIDE_SIDEBAR = "TOGGLE_HIDE_SIDEBAR";
