export const INCREMENT_STORY_POINTS_ACHIEVED_REQUEST = "INCREMENT_STORY_POINTS_ACHIEVED_REQUEST";
export const INCREMENT_STORY_POINTS_ACHIEVED_SUCCESS = "INCREMENT_STORY_POINTS_ACHIEVED_SUCCESS";
export const INCREMENT_STORY_POINTS_ACHIEVED_FAILURE = "INCREMENT_STORY_POINTS_ACHIEVED_FAILURE";
export const FETCH_REPORTS_DATA_REQUEST = "FETCH_REPORTS_DATA_REQUEST";
export const FETCH_REPORTS_DATA_SUCCESS = "FETCH_REPORTS_DATA_SUCCESS";
export const FETCH_REPORTS_DATA_FAILURE = "FETCH_REPORTS_DATA_FAILURE";


