export const SEARCH_MEMBER_REQUEST = "SEARCH_MEMBER_REQUEST";
export const SEARCH_MEMBER_SUCCESS = "SEARCH_MEMBER_SUCCESS";
export const SEARCH_MEMBER_FAIL = "SEARCH_MEMBER_FAIL";
export const ADD_MEMBER = "ADD_MEMBER";
