export const FETCH_DEVELOPERS_PROJECT_REQUEST = "FETCH_DEVELOPERS_PROJECT_REQUEST";
export const FETCH_DEVELOPERS_PROJECT_SUCCESS = "FETCH_DEVELOPERS_PROJECT_SUCCESS";
export const FETCH_DEVELOPERS_PROJECT_FAILURE = "FETCH_DEVELOPERS_PROJECT_FAILURE";

